adobe/react-native-acpcore

- .circleci/config.yml
- Makefile
- ios/Podfile.lock
- package.json
> Add build sample to CI steps (Core)

- android/build.gradle
- ios/libs/include/ACPCore.h
- ios/libs/include/ACPIdentity.h
- package-lock.json
- package.json
> Update Core libs for 1.0.3

- Makefile
- README.md
> Add testing instructions

- android/src/main/java/com/adobe/marketing/mobile/reactnative/RCTACPArrayUtil.java
- android/src/main/java/com/adobe/marketing/mobile/reactnative/RCTACPCoreDataBridge.java
- android/src/main/java/com/adobe/marketing/mobile/reactnative/RCTACPIdentityDataBridge.java
- android/src/main/java/com/adobe/marketing/mobile/reactnative/RCTACPMapUtil.java
- ios/src/Data-Bridging/ACPExtensionEvent+ReactNative.m
> Add NPE checks

- android/build.gradle
- ios/libs/include/ACPCore.h
- ios/libs/include/ACPIdentity.h
- package-lock.json
- package.json
> Version 1.0.4

- Makefile
- update-android-sdk.sh
> Automate android update

- ios/Podfile.lock
- package-lock.json
- package.json
> Trim down dependencies

- README.md
- __tests__/ACPIdentityTests.js
- android/src/main/java/com/adobe/marketing/mobile/reactnative/RCTACPIdentityModule.java
- ios/src/Identity/RCTACPIdentity.m
- jest/setup.js
- js/ACPIdentity.js
- sample/ACPCoreSample/App.js
* Add API for Identity.getUrlVariables
* Add jest mock and unit test for Identity.getUrlVariables
* Add manual test for Identity.getUrlVariables
* update README.md with Identity.getUrlVariables API
* fixes to ios Identity.getUrlVariables
> Add ACPIdentity.getUrlVariables API (#15)

- ios/RCTACPCore.xcodeproj/project.pbxproj
- sample/ACPCoreSample/ios/ACPCoreSample/Images.xcassets/AppIcon.appiconset/Contents.json
> Remove copy headers phase

- android/build.gradle
- ios/libs/include/ACPCore.h
- package-lock.json
- package.json
> 1.0.6 version

- ios/src/Core/RCTACPCore.m
> Fix set push identifier iOS

- package-lock.json
- package.json
> Version 1.0.7

- sample/ACPCoreSample/package-lock.json
- sample/ACPCoreSample/package.json
> Update sample app versions

- RCTACPCore.podspec
- README.md
- ios/Podfile
- ios/Podfile.lock
- ios/src/Core/RCTACPCore.h
- ios/src/Identity/RCTACPIdentity.h
- ios/src/Lifecycle/RCTACPLifecycle.h
- ios/src/Signal/RCTACPSignal.h
- package-lock.json
- package.json
Fixes https://github.com/adobe/react-native-acpcore/issues/31, https://github.com/adobe/react-native-acpcore/issues/2
> RN 0.60.0 (Add podspec)

- android/build.gradle
- ios/libs/include/ACPCore.h
- ios/libs/include/ACPIdentity.h
- package-lock.json
- package.json
> Version 1.1.2

- .editorconfig
- .npmignore
Added [editorconfig](https://editorconfig.org/) configuration.
EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs.
> feat: add .editorconfig

- android/build.gradle
- ios/libs/include/ACPCore.h
- package-lock.json
- package.json
> Version 1.1.3

- __tests__/ACPCoreTests.js
- android/src/main/java/com/adobe/marketing/mobile/reactnative/RCTACPCoreModule.java
- ios/src/Core/RCTACPCore.m
- js/ACPCore.js
API not applicable/valid in JS
> Remove collectLaunchInfo

- ios/libs/include/ACPIdentity.h
- package-lock.json
- package.json
> Version 1.2.0

- package-lock.json
- package.json
> version v1.2.1

- android/build.gradle
- package-lock.json
- package.json
> Version 1.2.2

- sample/ACPCoreSample/android/app/src/main/java/com/acpcoresample/MainApplication.java
- sample/ACPCoreSample/ios/ACPCoreSample/AppDelegate.m
> Add Lifecycle implementation to sample app

- android/build.gradle
- ios/libs/include/ACPCore.h
- ios/libs/include/ACPNetworkServiceOverrider.h
- package-lock.json
- package.json
> Version 1.2.4

- flow-typed/npm/eslint_vx.x.x.js
- sample/ACPCoreSample/.flowconfig
> Remove use of specific terms

- .github/workflows/npm-publish.yml
> fix publish

- sample/ACPCoreSampleApp/README.md
- sample/ACPCoreSampleApp/android/build.gradle
> add README for the sample app

- sample/ACPCoreTVapp/App.js
- sample/ACPCoreTVapp/android/app/src/main/java/com/acpcoretvapp/MainActivity.java
- sample/ACPCoreTVapp/android/app/src/main/java/com/acpcoretvapp/MainApplication.java
- sample/ACPCoreTVapp/index.js
- sample/ACPCoreTVapp/ios/ACPCoreTVapp/AppDelegate.h
- sample/ACPCoreTVapp/ios/ACPCoreTVappTests/ACPCoreTVappTests.m
> add copyright header to the sample code

- sample/ACPCoreSampleApp/android/app/src/main/java/com/acpcoresampleapp/MainActivity.java
- sample/ACPCoreSampleApp/ios/ACPCoreSampleAppTests/ACPCoreSampleAppTests.m
- sample/ACPCoreTVapp/App.js
- sample/ACPCoreTVapp/android/app/src/main/java/com/acpcoretvapp/MainActivity.java
- sample/ACPCoreTVapp/android/app/src/main/java/com/acpcoretvapp/MainApplication.java
- sample/ACPCoreTVapp/index.js
- sample/ACPCoreTVapp/ios/ACPCoreTVapp/AppDelegate.h
- sample/ACPCoreTVapp/ios/ACPCoreTVapp/main.m
- sample/ACPCoreTVapp/ios/ACPCoreTVappTests/ACPCoreTVappTests.m
> add copyright header to the sample code (2)

- ios/RCTACPCore.xcodeproj/project.pbxproj
- package-lock.json
- package.json
- sample/ACPCoreSampleApp/Makefile
- sample/ACPCoreSampleApp/android/app/src/main/java/com/acpcoresampleapp/MainActivity.java
- sample/ACPCoreSampleApp/ios/ACPCoreSampleAppTests/ACPCoreSampleAppTests.m
- sample/ACPCoreSampleApp/ios/Podfile.lock
- sample/ACPCoreSampleApp/package-lock.json
- sample/ACPCoreSampleApp/package.json
- sample/ACPCoreSampleApp/yarn.lock
- sample/ACPCoreTVapp/App.js
- sample/ACPCoreTVapp/android/app/src/main/java/com/acpcoretvapp/MainActivity.java
- sample/ACPCoreTVapp/android/app/src/main/java/com/acpcoretvapp/MainApplication.java
- sample/ACPCoreTVapp/index.js
- sample/ACPCoreTVapp/ios/ACPCoreTVapp/AppDelegate.h
- sample/ACPCoreTVapp/ios/ACPCoreTVapp/main.m
- sample/ACPCoreTVapp/ios/ACPCoreTVappTests/ACPCoreTVappTests.m
> Prepare for the (2.0.0) alpha release

- .github/workflows/npm-manual-publish.yml
> Add a manually triggered Github action for npm release
